name: "The example of ai code reviewer"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  example:
    uses: exampler0906/ai_reviewer/.github/workflows/code_review.yml@main  # 引用可复用的工作流
    with:
      pull_request_id: ${{ github.event.pull_request.number }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      LLM_API_URL: ${{ secrets.LLM_API_URL }}
      GITHUB_TOKEN: ${{ secrets.THIS_GITHUB_TOKEN }}
      REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
      REPOSITORY_OWNER: ${{ secrets.REPOSITORY_OWNER }}
      PROMPT_LEVEL: ${{ secrets.PROMPT_LEVEL }}
